name: CI -> Deploy to My website
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload Laravel Project via SCP
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          scp -r ./ algobot@algobot048.com:/home2/algobot/old.algobot048.com
        env:
          USER: algobot
          PASSWORD: syzh3lpf4187
