name: Deploy Laravel Project to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        with:
          ftp-server: ftp://ftp.algobot048.com/
          ftp-username: ecom@old.algobot048.com
          ftp-password: 4kg4Y*@yPKm$
